"""add scan tasks

Revision ID: dc1978d3a295
Revises: c4b890b43e9b
Create Date: 2026-08-09 09:42:44.074708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1978d3a295'
down_revision: Union[str, Sequence[str], None] = 'c4b890b43e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('query_kind', sa.String(length=100), nullable=False),
    sa.Column('query_value', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('removal_url', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requires_human_verification', sa.Boolean(), nullable=False),
    sa.Column('result_url', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['privacy_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_tasks_profile_id'), 'scan_tasks', ['profile_id'], unique=False)
    op.create_index(op.f('ix_scan_tasks_source_key'), 'scan_tasks', ['source_key'], unique=False)
    op.create_index(op.f('ix_scan_tasks_status'), 'scan_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_tasks_status'), table_name='scan_tasks')
    op.drop_index(op.f('ix_scan_tasks_source_key'), table_name='scan_tasks')
    op.drop_index(op.f('ix_scan_tasks_profile_id'), table_name='scan_tasks')
    op.drop_table('scan_tasks')
    # ### end Alembic commands ###
